import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Kampee's resume",
  description: "Generated by aecuto",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
